<?php

namespace EP\DoctrineLockBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * ArticleAuthorRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ObjectLockRepository extends EntityRepository
{
}